#!/bin/bash

# VPN Setup Script for Checklist Creator
# This script sets up OpenVPN and basic VPN configuration

set -e  # Exit on any error

echo "🔒 Setting up VPN environment for Checklist Creator..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
if [[ $EUID -eq 0 ]]; then
   print_error "This script should not be run as root. Please run as a regular user with sudo privileges."
   exit 1
fi

# Update system packages
print_status "Updating system packages..."
sudo apt update

# Install OpenVPN and related packages
print_status "Installing OpenVPN and related packages..."
sudo apt install -y \
    openvpn \
    openvpn-systemd-resolved \
    resolvconf \
    iptables \
    net-tools \
    curl \
    wget

# Create VPN configuration directories
print_status "Creating VPN configuration directories..."
sudo mkdir -p /etc/openvpn/{client,server,configs}
sudo mkdir -p /var/log/openvpn
sudo chown -R $USER:$USER /etc/openvpn/configs
sudo chown -R $USER:$USER /var/log/openvpn

# Create VPN configuration file
print_status "Creating VPN configuration file..."
sudo tee /etc/openvpn/client.conf > /dev/null << 'EOF'
# OpenVPN Client Configuration
# Generated by Checklist Creator VPN Setup

# Network configuration
dev tun
proto udp
remote 127.0.0.1 1194
resolv-retry infinite

# Security
nobind
persist-key
persist-tun
remote-cert-tls server
cipher AES-256-CBC
auth SHA256

# Authentication
auth-user-pass /etc/openvpn/auth.txt

# Logging
verb 3
log /var/log/openvpn/client.log

# DNS
script-security 2
up /etc/openvpn/update-resolv-conf
down /etc/openvpn/update-resolv-conf
EOF

# Create authentication file template
print_status "Creating authentication file template..."
sudo tee /etc/openvpn/auth.txt > /dev/null << 'EOF'
# OpenVPN Authentication File
# Replace with your actual credentials
# Format: username on first line, password on second line
username
password
EOF

# Set proper permissions
sudo chmod 600 /etc/openvpn/auth.txt
sudo chown root:root /etc/openvpn/auth.txt

# Create sample OpenVPN configuration files
print_status "Creating sample OpenVPN configurations..."

# US East configuration
cat > /etc/openvpn/configs/us-east.ovpn << 'EOF'
# US East OpenVPN Configuration
client
dev tun
proto udp
remote us-east.vpn.example.com 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
cipher AES-256-CBC
auth SHA256
auth-user-pass auth.txt
verb 3
EOF

# US West configuration
cat > /etc/openvpn/configs/us-west.ovpn << 'EOF'
# US West OpenVPN Configuration
client
dev tun
proto udp
remote us-west.vpn.example.com 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
cipher AES-256-CBC
auth SHA256
auth-user-pass auth.txt
verb 3
EOF

# Europe configuration
cat > /etc/openvpn/configs/eu-west.ovpn << 'EOF'
# Europe West OpenVPN Configuration
client
dev tun
proto udp
remote eu-west.vpn.example.com 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
cipher AES-256-CBC
auth SHA256
auth-user-pass auth.txt
verb 3
EOF

# Asia configuration
cat > /etc/openvpn/configs/asia-east.ovpn << 'EOF'
# Asia East OpenVPN Configuration
client
dev tun
proto udp
remote asia-east.vpn.example.com 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
cipher AES-256-CBC
auth SHA256
auth-user-pass auth.txt
verb 3
EOF

# Create VPN management script
print_status "Creating VPN management script..."
cat > ~/checklist_creator/scripts/manage_vpn.sh << 'EOF'
#!/bin/bash

# VPN Management Script for Checklist Creator
# This script provides easy VPN management commands

VPN_CONFIG_DIR="/etc/openvpn/configs"
VPN_LOG_DIR="/var/log/openvpn"

case "$1" in
    "status")
        echo "🔍 Checking VPN status..."
        if pgrep -f "openvpn" > /dev/null; then
            echo "✅ OpenVPN is running"
            ps aux | grep openvpn | grep -v grep
        else
            echo "❌ OpenVPN is not running"
        fi
        
        # Check current IP
        echo "🌐 Current IP address:"
        curl -s https://httpbin.org/ip | grep -o '"origin":"[^"]*"' | cut -d'"' -f4
        ;;
    
    "connect")
        if [ -z "$2" ]; then
            echo "Usage: $0 connect <config-name>"
            echo "Available configs:"
            ls -1 $VPN_CONFIG_DIR/*.ovpn | sed 's/.*\///' | sed 's/\.ovpn$//'
            exit 1
        fi
        
        CONFIG_FILE="$VPN_CONFIG_DIR/$2.ovpn"
        if [ ! -f "$CONFIG_FILE" ]; then
            echo "❌ Configuration file $CONFIG_FILE not found"
            exit 1
        fi
        
        echo "🔌 Connecting to VPN using $2 configuration..."
        sudo openvpn --config "$CONFIG_FILE" --daemon
        sleep 3
        
        if pgrep -f "openvpn" > /dev/null; then
            echo "✅ VPN connected successfully"
        else
            echo "❌ VPN connection failed"
        fi
        ;;
    
    "disconnect")
        echo "🔌 Disconnecting VPN..."
        sudo pkill -f "openvpn"
        sleep 2
        
        if pgrep -f "openvpn" > /dev/null; then
            echo "❌ Failed to disconnect VPN"
        else
            echo "✅ VPN disconnected successfully"
        fi
        ;;
    
    "logs")
        echo "📋 VPN logs:"
        if [ -f "$VPN_LOG_DIR/client.log" ]; then
            tail -20 "$VPN_LOG_DIR/client.log"
        else
            echo "No VPN logs found"
        fi
        ;;
    
    "test")
        echo "🧪 Testing VPN connection..."
        
        # Test basic connectivity
        if ping -c 1 8.8.8.8 > /dev/null 2>&1; then
            echo "✅ Basic connectivity: OK"
        else
            echo "❌ Basic connectivity: FAILED"
        fi
        
        # Test DNS resolution
        if nslookup google.com > /dev/null 2>&1; then
            echo "✅ DNS resolution: OK"
        else
            echo "❌ DNS resolution: FAILED"
        fi
        
        # Test external IP
        echo "🌐 External IP address:"
        curl -s https://httpbin.org/ip | grep -o '"origin":"[^"]*"' | cut -d'"' -f4
        ;;
    
    "install-config")
        if [ -z "$2" ]; then
            echo "Usage: $0 install-config <config-file>"
            echo "This will install a new OpenVPN configuration file"
            exit 1
        fi
        
        if [ ! -f "$2" ]; then
            echo "❌ File $2 not found"
            exit 1
        fi
        
        CONFIG_NAME=$(basename "$2" .ovpn)
        echo "📁 Installing configuration: $CONFIG_NAME"
        sudo cp "$2" "$VPN_CONFIG_DIR/"
        sudo chown root:root "$VPN_CONFIG_DIR/$CONFIG_NAME.ovpn"
        sudo chmod 644 "$VPN_CONFIG_DIR/$CONFIG_NAME.ovpn"
        echo "✅ Configuration installed successfully"
        ;;
    
    "list-configs")
        echo "📁 Available VPN configurations:"
        ls -1 $VPN_CONFIG_DIR/*.ovpn | sed 's/.*\///' | sed 's/\.ovpn$//'
        ;;
    
    *)
        echo "Usage: $0 {status|connect|disconnect|logs|test|install-config|list-configs}"
        echo ""
        echo "Commands:"
        echo "  status          - Check VPN status"
        echo "  connect <name>  - Connect to VPN using specified config"
        echo "  disconnect      - Disconnect from VPN"
        echo "  logs            - Show VPN logs"
        echo "  test            - Test VPN connection"
        echo "  install-config  - Install new OpenVPN configuration"
        echo "  list-configs    - List available configurations"
        echo ""
        echo "Examples:"
        echo "  $0 status"
        echo "  $0 connect us-east"
        echo "  $0 disconnect"
        echo "  $0 install-config ~/Downloads/my-vpn.ovpn"
        exit 1
        ;;
esac
EOF

# Make VPN management script executable
chmod +x ~/checklist_creator/scripts/manage_vpn.sh

# Create VPN configuration file
print_status "Creating VPN configuration for Checklist Creator..."
mkdir -p ~/checklist_creator/config
cat > ~/checklist_creator/config/vpn_config.json << 'EOF'
{
  "providers": {
    "openvpn": {
      "name": "openvpn",
      "config_path": "/etc/openvpn/configs",
      "credentials_path": "/etc/openvpn/auth.txt",
      "servers": ["us-east", "us-west", "eu-west", "asia-east"],
      "locations": ["United States", "Europe", "Asia"],
      "max_connections": 1,
      "health_check_url": "https://httpbin.org/ip",
      "timeout": 30
    }
  },
  "health_check_interval": 30,
  "max_reconnect_attempts": 3
}
EOF

# Create VPN test script
print_status "Creating VPN test script..."
cat > ~/checklist_creator/scripts/test_vpn.py << 'EOF'
#!/usr/bin/env python3
"""
VPN Test Script for Checklist Creator
Tests the VPN functionality and API endpoints
"""

import asyncio
import sys
import os

# Add the backend directory to the Python path
sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'backend'))

from core.vpn_manager import VPNManager

async def test_vpn_manager():
    """Test the VPN manager functionality"""
    print("🧪 Testing VPN Manager...")
    
    try:
        # Initialize VPN manager
        vpn_manager = VPNManager("config/vpn_config.json")
        print("✅ VPN Manager initialized successfully")
        
        # Get status
        status = vpn_manager.get_status()
        print(f"📊 VPN Status: {status['status']}")
        print(f"🔌 Available Providers: {status['available_providers']}")
        
        # Test IP detection
        print("🌐 Testing IP detection...")
        current_ip = await vpn_manager._get_current_ip()
        if current_ip:
            print(f"✅ Current IP: {current_ip}")
        else:
            print("❌ Failed to get current IP")
        
        # Test ping
        print("🏓 Testing ping...")
        ping_result = await vpn_manager._ping_test("8.8.8.8")
        if ping_result > 0:
            print(f"✅ Ping to 8.8.8.8: {ping_result}ms")
        else:
            print("❌ Ping test failed")
        
        print("\n🎉 VPN Manager test completed successfully!")
        
    except Exception as e:
        print(f"❌ VPN Manager test failed: {e}")
        return False
    
    return True

if __name__ == "__main__":
    print("🚀 Starting VPN Manager Test...")
    success = asyncio.run(test_vpn_manager())
    
    if success:
        print("\n✅ All tests passed!")
        sys.exit(0)
    else:
        print("\n❌ Some tests failed!")
        sys.exit(1)
EOF

# Make test script executable
chmod +x ~/checklist_creator/scripts/test_vpn.py

# Create systemd service for OpenVPN
print_status "Creating OpenVPN systemd service..."
sudo tee /etc/systemd/system/openvpn-client@.service > /dev/null << 'EOF'
[Unit]
Description=OpenVPN Client Service for %I
After=network.target
Wants=network.target

[Service]
Type=forking
ExecStart=/usr/sbin/openvpn --config /etc/openvpn/configs/%i.ovpn --daemon
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target
EOF

# Reload systemd
sudo systemctl daemon-reload

# Create VPN health check script
print_status "Creating VPN health check script..."
cat > ~/checklist_creator/scripts/vpn_health_check.sh << 'EOF'
#!/bin/bash

# VPN Health Check Script
# Monitors VPN connection health and reports status

echo "🔍 VPN Health Check - $(date)"

# Check if OpenVPN is running
if pgrep -f "openvpn" > /dev/null; then
    echo "✅ OpenVPN process: RUNNING"
    
    # Check connection status
    if curl -s --connect-timeout 10 https://httpbin.org/ip > /dev/null; then
        echo "✅ Internet connectivity: OK"
        
        # Get current IP
        CURRENT_IP=$(curl -s https://httpbin.org/ip | grep -o '"origin":"[^"]*"' | cut -d'"' -f4)
        echo "🌐 Current IP: $CURRENT_IP"
        
        # Test ping
        if ping -c 1 8.8.8.8 > /dev/null 2>&1; then
            echo "✅ Ping test: OK"
        else
            echo "❌ Ping test: FAILED"
        fi
        
    else
        echo "❌ Internet connectivity: FAILED"
    fi
    
else
    echo "❌ OpenVPN process: NOT RUNNING"
fi

echo "---"
EOF

# Make health check script executable
chmod +x ~/checklist_creator/scripts/vpn_health_check.sh

# Create VPN configuration guide
print_status "Creating VPN configuration guide..."
cat > ~/checklist_creator/docs/vpn_setup_guide.md << 'EOF'
# VPN Setup Guide for Checklist Creator

## Overview

This guide explains how to set up and configure VPN connections for the Checklist Creator project.

## Prerequisites

- Ubuntu 22.04 LTS
- OpenVPN installed
- Sudo privileges
- VPN provider credentials

## Configuration Files

### 1. OpenVPN Configuration Files

Configuration files are stored in `/etc/openvpn/configs/` and should have the `.ovpn` extension.

Example configuration structure:
```
/etc/openvpn/configs/
├── us-east.ovpn      # US East Coast
├── us-west.ovpn      # US West Coast
├── eu-west.ovpn      # Europe West
└── asia-east.ovpn    # Asia East
```

### 2. Authentication File

The authentication file `/etc/openvpn/auth.txt` contains your VPN credentials:
```
username
password
```

**Important**: Keep this file secure and set proper permissions (600).

## Usage

### Basic Commands

1. **Check VPN Status**:
   ```bash
   ./scripts/manage_vpn.sh status
   ```

2. **Connect to VPN**:
   ```bash
   ./scripts/manage_vpn.sh connect us-east
   ```

3. **Disconnect from VPN**:
   ```bash
   ./scripts/manage_vpn.sh disconnect
   ```

4. **Test VPN Connection**:
   ```bash
   ./scripts/manage_vpn.sh test
   ```

### API Endpoints

Once the application is running, you can use these API endpoints:

- `GET /api/v1/vpn/status` - Get VPN status
- `POST /api/v1/vpn/connect` - Connect to VPN
- `POST /api/v1/vpn/disconnect` - Disconnect from VPN
- `GET /api/v1/vpn/health` - Check VPN health
- `GET /api/v1/vpn/metrics` - Get performance metrics

## Adding New VPN Configurations

1. **Obtain Configuration File**: Download `.ovpn` file from your VPN provider
2. **Install Configuration**:
   ```bash
   ./scripts/manage_vpn.sh install-config ~/Downloads/my-vpn.ovpn
   ```
3. **Update Configuration**: Edit the configuration file if needed
4. **Test Connection**: Use the test command to verify

## Troubleshooting

### Common Issues

1. **Permission Denied**: Ensure proper file permissions
2. **Connection Failed**: Check credentials and configuration
3. **DNS Issues**: Verify DNS configuration in OpenVPN config

### Logs

Check VPN logs for detailed error information:
```bash
./scripts/manage_vpn.sh logs
```

### Health Monitoring

Run regular health checks:
```bash
./scripts/vpn_health_check.sh
```

## Security Considerations

- Keep authentication files secure
- Use strong passwords
- Regularly update OpenVPN
- Monitor connection logs
- Use firewall rules appropriately

## Next Steps

After setting up VPN configurations:

1. Test basic connectivity
2. Configure the application
3. Set up automated health monitoring
4. Test failover scenarios
EOF

# Final setup
print_status "Finalizing VPN setup..."

# Test OpenVPN installation
if command -v openvpn > /dev/null; then
    print_success "OpenVPN installed successfully"
else
    print_error "OpenVPN installation failed"
    exit 1
fi

# Test configuration files
if [ -f "/etc/openvpn/configs/us-east.ovpn" ]; then
    print_success "VPN configuration files created successfully"
else
    print_error "VPN configuration files creation failed"
    exit 1
fi

# Print completion message
print_success "VPN setup completed successfully!"
echo ""
echo "🎉 Your VPN environment is ready for Checklist Creator!"
echo ""
echo "📁 Configuration files: /etc/openvpn/configs/"
echo "🔑 Authentication file: /etc/openvpn/auth.txt"
echo "📋 Management script: ~/checklist_creator/scripts/manage_vpn.sh"
echo "🧪 Test script: ~/checklist_creator/scripts/test_vpn.py"
echo "📚 Setup guide: ~/checklist_creator/docs/vpn_setup_guide.md"
echo ""
echo "🚀 Quick start commands:"
echo "  cd ~/checklist_creator"
echo "  ./scripts/manage_vpn.sh status"
echo "  ./scripts/manage_vpn.sh connect us-east"
echo "  ./scripts/test_vpn.py"
echo ""
echo "⚠️  IMPORTANT: Update /etc/openvpn/auth.txt with your actual VPN credentials!"
echo ""
print_success "VPN setup complete! Happy secure browsing! 🔒"
