#!/usr/bin/env python3
"""
Simple VPN Connection Test
Tests VPN connection with manual server configuration
"""

import asyncio
import sys
import subprocess
import time
from pathlib import Path

# Add the backend directory to the Python path
backend_path = Path(__file__).parent.parent / "backend"
sys.path.insert(0, str(backend_path))

from core.credential_manager import get_credential_manager

async def test_vyprvpn_connection():
    """Test VyprVPN connection with manual server"""
    print("🔐 Testing VyprVPN Connection (Manual Server)")
    print("=" * 50)
    
    try:
        # Get credentials
        credential_manager = get_credential_manager()
        credentials = credential_manager.get_vyprvpn_credentials()
        
        if not credentials:
            print("❌ No VyprVPN credentials found!")
            print("Please set up credentials first:")
            print("python3 scripts/manage_credentials.py setup-vyprvpn")
            return False
        
        username = credentials.get('username')
        password = credentials.get('password')
        
        print(f"✅ Credentials loaded for user: {username}")
        
        # Use a known VyprVPN server (we'll use a common one)
        server_hostname = "us1.vyprvpn.com"  # Common US server
        
        print(f"🎯 Attempting connection to: {server_hostname}")
        
        # Create auth file
        auth_file = create_auth_file(username, password)
        print(f"📝 Auth file created: {auth_file}")
        
        # Create OpenVPN config
        config_file = create_openvpn_config(server_hostname, auth_file)
        print(f"⚙️ OpenVPN config created: {config_file}")
        
        # Test OpenVPN availability
        if not check_openvpn():
            print("❌ OpenVPN is not available")
            return False
        
        # Attempt connection
        print("🔌 Starting OpenVPN connection...")
        result = await connect_openvpn(config_file, auth_file)
        
        if result['success']:
            print("✅ VPN Connection Successful!")
            print(f"   Server: {server_hostname}")
            print(f"   Message: {result['message']}")
            
            # Test IP change
            print("\n🌐 Testing IP address change...")
            await test_ip_change()
            
            return True
        else:
            print("❌ VPN Connection Failed!")
            print(f"   Error: {result['error']}")
            return False
            
    except Exception as e:
        print(f"❌ Connection test failed: {e}")
        import traceback
        traceback.print_exc()
        return False

def create_auth_file(username: str, password: str) -> str:
    """Create temporary auth file"""
    temp_dir = Path("/tmp/checklist_creator_vpn")
    temp_dir.mkdir(exist_ok=True)
    
    auth_file = temp_dir / f"auth_{int(time.time())}.txt"
    
    with open(auth_file, 'w') as f:
        f.write(f"{username}\n{password}\n")
    
    auth_file.chmod(0o600)
    return str(auth_file)

def create_openvpn_config(server_hostname: str, auth_file: str) -> str:
    """Create OpenVPN config file"""
    temp_dir = Path("/tmp/checklist_creator_vpn")
    temp_dir.mkdir(exist_ok=True)
    
    config_file = temp_dir / f"vyprvpn_{int(time.time())}.ovpn"
    
    config_content = f"""# VyprVPN OpenVPN Configuration
# Generated by Checklist Creator
client
dev tun
proto udp
remote {server_hostname} 1194
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
cipher AES-256-CBC
auth SHA256
auth-user-pass {auth_file}
verb 3
"""
    
    with open(config_file, 'w') as f:
        f.write(config_content)
    
    return str(config_file)

def check_openvpn() -> bool:
    """Check if OpenVPN is available"""
    try:
        result = subprocess.run(['openvpn', '--version'], 
                              capture_output=True, check=True)
        return True
    except (subprocess.CalledProcessError, FileNotFoundError):
        return False

async def connect_openvpn(config_file: str, auth_file: str) -> dict:
    """Establish OpenVPN connection"""
    try:
        print("Starting OpenVPN process...")
        
        # Start OpenVPN process
        process = subprocess.Popen([
            'openvpn',
            '--config', config_file,
            '--daemon'
        ], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
        
        # Wait for connection to establish
        print("Waiting for connection to establish...")
        await asyncio.sleep(5)
        
        # Check if process is still running
        if process.poll() is None:
            print("OpenVPN process is running")
            
            # Test connectivity
            if await test_connectivity():
                return {
                    'success': True,
                    'message': 'VPN connection established successfully',
                    'process': process
                }
            else:
                return {
                    'success': False,
                    'error': 'VPN process started but connectivity test failed'
                }
        else:
            # Process failed
            stdout, stderr = process.communicate()
            return {
                'success': False,
                'error': f'OpenVPN process failed: {stderr.decode()}'
            }
            
    except Exception as e:
        return {
            'success': False,
            'error': str(e)
        }

async def test_connectivity() -> bool:
    """Test basic connectivity"""
    try:
        # Test ping to Google DNS
        result = subprocess.run(['ping', '-c', '1', '8.8.8.8'], 
                              capture_output=True, timeout=5)
        return result.returncode == 0
    except Exception:
        return False

async def test_ip_change():
    """Test if IP address changed"""
    try:
        import requests
        
        print("Getting current IP address...")
        response = requests.get('https://httpbin.org/ip', timeout=10)
        current_ip = response.json()['origin']
        print(f"Current IP: {current_ip}")
        
        print("✅ IP address retrieved successfully")
        print("Note: To verify IP change, you would need to check your IP before and after VPN connection")
        
    except ImportError:
        print("⚠️ requests module not available, skipping IP check")
    except Exception as e:
        print(f"❌ IP check failed: {e}")

async def main():
    """Main test function"""
    print("🚀 Simple VPN Connection Test")
    print("=" * 50)
    
    try:
        success = await test_vyprvpn_connection()
        
        if success:
            print("\n🎉 VPN connection test completed successfully!")
            print("\n📋 Next steps:")
            print("1. Check if your IP address has changed")
            print("2. Test internet connectivity")
            print("3. Disconnect when done: sudo pkill openvpn")
            return 0
        else:
            print("\n💥 VPN connection test failed!")
            return 1
            
    except KeyboardInterrupt:
        print("\n\n⏹️ Test cancelled by user")
        return 1
    except Exception as e:
        print(f"\n❌ Unexpected error: {e}")
        return 1

if __name__ == "__main__":
    exit_code = asyncio.run(main())
    sys.exit(exit_code)
